version: 2.1

jobs:
  run-deluge:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout

      # Install Deluge and dependencies
      - run:
          name: "Install Deluge"
          command: |
            sudo apt-get update && \
            sudo apt-get install -y deluged deluge-console

      # Start Deluge daemon
      - run:
          name: "Start Deluge Daemon"
          command: |
            deluged &
            sleep 10  # Wait for the daemon to start

      # Add a magnet link using Deluge Console
      - run:
          name: "Add torrent using Deluge Console"
          command: |
            deluge-console add "magnet:?xt=urn:btih:0D4AF725CC7CDF3CE933E5BFF8C0B3A6ED6E0D93&dn=Python+Programming+And+Maching+Learning+Understanding+How+To+Cod"

      # Wait a fixed time before checking the torrent status
      - run:
          name: "Wait before checking Torrent Status"
          command: |
            sleep 120  # Waiting for 120 seconds (2 minutes) for the download to progress.

      # Check the torrent status once to see if it has completed.
      - run:
          name: "Check Torrent Status"
          command: |
            state=$(deluge-console info | grep 'State:' | awk '{print $2}')
            if [[ "$state" == "Finished" ]]; then
              echo "Torrent download is complete."
            else
              echo "Torrent download is still in progress or failed. Current state: $state"
              exit 1  # Exit with error as download did not complete
            fi

      # List downloaded files if the download is complete
      - run:
          name: "List Downloaded Files"
          command: |
            download_dir="$HOME/Downloads"  # Confirm this path with your Deluge setup
            echo "Files in $download_dir:"
            ls -lh "$download_dir"

      # Store the downloaded files as CircleCI artifacts
      - store_artifacts:
          path: "$HOME/Downloads"  # Adjust to actual download directory
          destination: downloaded_files  # Name for the artifacts

      # Stop the Deluge Daemon after tasks are done
      - run:
          name: "Stop Deluge Daemon"
          command: killall deluged

workflows:
  download-torrent-workflow:
    jobs:
      - run-deluge
