version: 2.1

jobs:
  download_and_upload:
    docker:
      - image: cimg/node:18.17
    environment:
      TORRENT_MAGNET: "magnet:?xt=urn:btih:8F86D38E13D6D295477E3EBF05494A030333637A&dn=Ke+X.+Space-Time+Coding+Theory+in+Optical+Wireless+MIMO+Systems+2025&tr=udp://tracker.bittor.pw:1337/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.dler.org:6969/announce&tr=udp://open.stealth.si:80/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://open.demonii.com:1337/announce"
      PIXELDRAIN_API_KEY: "8ec6f000-e8d1-403d-820b-4324a6a68869"  # replace or use project env var
    steps:
      - checkout     
      - run:
          name: Download files
          command: |          
            mkdir -p downloads
            curl -s https://klipit.in/ugq73679 | grep -oP 'http[s]?://[^"'\'' >]+?\.(mp4|mkv)' > download_links.txt
            cat download_links.txt | xargs -n 1 -P 4 wget --content-disposition --no-check-certificate -P downloads
      - run:
          name: Upload files to buzzheavier.com
          command: |
            # Set your local directory inside the container
            LOCAL_DIR="downloads"
            TARGET_URL="https://w.buzzheavier.com/bnyznwosiir7"
            ACCOUNT_ID="HZ7U0SXV0YKJYO0C77ZI"  # Replace with your actual account ID
            
            # Loop through all files in the downloads directory
            find "$LOCAL_DIR" -type f | while read -r FILE; do
                FILENAME=$(basename "$FILE")
                echo "Uploading $FILENAME..."
                curl -#o - -T "$FILE" \
                -H "Authorization: Bearer $ACCOUNT_ID" \
                "$TARGET_URL/$FILENAME"
            done

workflows:
  version: 2
  download_and_upload_workflow:
    jobs:
      - download_and_upload
