version: 2.1

executors:
  go-executor:
    docker:
      - image: golang:1.20  # Use the Go Docker image
    working_directory: ~/repo

jobs:
  setup:
    executor: go-executor
    steps:
      # Checkout the code from the repository
      - checkout
      
      # Install dependencies (ensure git and Go are installed, Go should already be in the golang Docker image)
      - run:
          name: Install Dependencies
          command: |
            go mod tidy  # Ensure Go modules are up-to-date
            
      # Build the Go project
      - run:
          name: Build Go Application
          command: |
            go build -o torrent-downloader ./  # Build the Go binary (adjust path as needed)
            
      # Run the Go program that uses Anacrolix to download torrents
      - run:
          name: Run Torrent Downloader
          command: |
            ./torrent-downloader  # Replace this with the correct command to run your application

workflows:
  version: 2
  build:
    jobs:
      - setup
