version: 2.1

jobs:
  run-deluge:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout

      # Install Deluge and dependencies
      - run:
          name: "Install Deluge"
          command: |
            sudo apt-get update && \
            sudo apt-get install -y deluged deluge-console

      # Start Deluge daemon
      - run:
          name: "Start Deluge Daemon"
          command: |
            deluged &
            sleep 10  # Wait for the daemon to start

      # Add a magnet link using Deluge Console
      - run:
          name: "Add torrent using Deluge Console"
          command: |
            deluge-console add "magnet:?xt=urn:btih:0D4AF725CC7CDF3CE933E5BFF8C0B3A6ED6E0D93&dn=Python+Programming+And+Maching+Learning+Understanding+How+To+Cod"

      # Wait for the torrent to finish downloading
      - run:
          name: "Wait for Torrent to Finish Downloading"
          command: |
            while true; do
              info=$(deluge-console info | grep "State:")
              if echo "$info" | grep -q "Seeding\|Stopped"; then
                echo "Torrent download is complete."
                break
              fi
              echo "Waiting for the torrent to finish downloading..."
              sleep 30  # Check every 30 seconds
            done

      # Stop the torrent and download files
      - run:
          name: "Stop Torrent Download"
          command: |
            deluge-console pause
            deluge-console remove "magnet:?xt=urn:btih:0D4AF725CC7CDF3CE933E5BFF8C0B3A6ED6E0D93&dn=Python+Programming+And+Maching+Learning+Understanding+How+To+Cod"
            echo "Torrent has been paused and removed from Deluge."

      # List downloaded files
      - run:
          name: "List Downloaded Files"
          command: |
            # Check Deluge's default download directory
            download_dir="$HOME/Downloads"
            echo "Files in $download_dir:"
            ls -lh "$download_dir"

      # Store the downloaded files as CircleCI artifacts
      - store_artifacts:
          path: "$HOME/Downloads"  # Adjust to actual download directory
          destination: downloaded_files  # Name for the artifacts

      # Stop the Deluge Daemon after tasks are done
      - run:
          name: "Stop Deluge Daemon"
          command: killall deluged

workflows:
  download-torrent-workflow:
    jobs:
      - run-deluge
