version: 2.1

executors:
  go-executor:
    docker:
      - image: golang:1.23  # Use the Go Docker image
    working_directory: ~/repo

jobs:
  setup:
    executor: go-executor
    steps:
      # Checkout the code from the repository
      - checkout
            
      # Build the Go project
      - run:
          name: Build Go Application
          command: |
            go install github.com/anacrolix/torrent@latest  # Build the Go binary (adjust path as needed)
            
      # Run the Go program that uses Anacrolix to download torrents
      - run:
          name: Run Torrent Downloader
          command: |
            ./torrent-downloader  # Replace this with the correct command to run your application

workflows:
  version: 2
  build:
    jobs:
      - setup
