version: 2.1

jobs:
  run-deluge:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout

      # Install Deluge and necessary dependencies
      - run:
          name: "Install Deluge"
          command: |
            sudo apt-get update && \
            sudo apt-get install -y deluged deluge-console

      # Start Deluge daemon
      - run:
          name: "Start Deluge Daemon"
          command: deluged &

      # Add a torrent using Deluge console
      - run:
          name: "Add torrent using Deluge Console"
          command: |
            deluge-console add "magnet:?xt=urn:btih:0D4AF725CC7CDF3CE933E5BFF8C0B3A6ED6E0D93&dn=Python+Programming+And+Maching+Learning+Understanding+How+To+Cod"

      # Optionally, wait for a few seconds for the torrent to be added
      - run:
          name: "Wait for Torrent to Start"
          command: sleep 30

      # You can also use deluge-console to check the status or perform further actions
      - run:
          name: "Check Deluge Status"
          command: deluge-console info

      # Just an example of stopping the daemon if needed
      - run:
          name: "Stop Deluge Daemon"
          command: killall deluged

workflows:
  download-torrent-workflow:
    jobs:
      - run-deluge
